import 'vuetify/styles'
import '@mdi/font/css/materialdesignicons.css'

import { createVuetify } from 'vuetify'
import {
  VAlert,
  VApp,
  VBtn,
  VCard,
  VCardActions,
  VCardSubtitle,
  VCardText,
  VCardTitle,
  VCheckbox,
  VChip,
  VDialog,
  VDivider,
  VExpansionPanel,
  VExpansionPanels,
  VExpansionPanelText,
  VForm,
  VIcon,
  VList,
  VListItem,
  VListItemSubtitle,
  VListItemTitle,
  VPagination,
  VProgressCircular,
  VSelect,
  VSkeletonLoader,
  VSpacer,
  VTab,
  VTable,
  VTabs,
  VTextField,
  VWindow,
  VWindowItem,
} from 'vuetify/components'

const sharedColors = {
  background: '#f8fafc',
  error: '#b91c1c',
  info: '#0369a1',
  primary: '#075985',
  secondary: '#475569',
  success: '#15803d',
  surface: '#ffffff',
  warning: '#a16207',
}

export const vuetify = createVuetify({
  components: {
    VAlert,
    VApp,
    VBtn,
    VCard,
    VCardActions,
    VCardSubtitle,
    VCardText,
    VCardTitle,
    VCheckbox,
    VChip,
    VDialog,
    VDivider,
    VExpansionPanel,
    VExpansionPanels,
    VExpansionPanelText,
    VForm,
    VIcon,
    VList,
    VListItem,
    VListItemSubtitle,
    VListItemTitle,
    VPagination,
    VProgressCircular,
    VSelect,
    VSkeletonLoader,
    VSpacer,
    VTab,
    VTable,
    VTabs,
    VTextField,
    VWindow,
    VWindowItem,
  },
  defaults: {
    VBtn: {
      rounded: 'lg',
    },
  },
  display: {
    mobileBreakpoint: 'md',
    thresholds: {
      xs: 0,
      sm: 640,
      md: 768,
      lg: 1024,
      xl: 1280,
      xxl: 1536,
    },
  },
  theme: {
    defaultTheme: 'pqs',
    themes: {
      pqs: {
        dark: false,
        colors: sharedColors,
      },
    },
  },
})
